### ISSUE TITLE
ResBaz 2018 website

### ISSUE THREAD

**Issue by DamienIrving** [resbaz/resbaz2018#1]
@tjdett I'm about to call the first community meeting for ResBaz 2018. Do you think any significant changes need to be made to this new website template, or should I simply rename it resbaz2018 (or create a copy called that), create `contributing.md` to explain to people how to create their site pages, and hit go?

**Comment by tjdett** [comment]
@DamienIrving I don't think any significant changes need to be made, though it's been a while since I've looked at it. Hobart is the only site page currently, so everybody else will have to copy from that example, but I think I covered most of the functionality people will want to use in their own site pages.
