### ISSUE TITLE
Load can be slow, leading users to sometimes see only the unformatted page (on Firefox only)

### ISSUE THREAD

**Issue by philippbayer** [resbaz/resbaz2018#2]
This is how it looks like for a few seconds, on slower connections it sometimes stays like this:

![image](https://user-images.githubusercontent.com/413885/31475213-29e8a4c4-af32-11e7-970f-222d7c296780.png)

Possible solutions:
- fade the page in as it loads, as in this gist: https://gist.github.com/ebidel/1ba71473d687d0567bd3
  problem is that this particular implementation won't work on the city-pages, lots of code duplication as they don't seem to inherit anything from index.html (or is this just because I'm checking on my local system?)
- polymer-bundler can smorsh the entire app into a single bigger html for faster loading, seems to fix the issue with index.html on my system: https://github.com/Polymer/polymer-bundler
  problem is this also doesn't work with the perth/hobart pages (again, locally, no clue how that would work with gh-pages)

**Comment by DamienIrving** [comment]
@tjdett Sorry to be a pest (I have no idea if you have time for this sort of thing these days), but any ideas on the page load delay?

**Comment by tjdett** [comment]
@philippbayer Are you seeing the slow behaviour on GitHub Pages, or just on your own desktop?

The "many files" approach the new version uses (to avoid the need to compile anything beforehand) works well with HTTP/2, but will look quite slow with HTTP 1.1. [Most browsers support HTTP/2](http://caniuse.com/#feat=http2) so it's unlikely that you'll see a problem due to that when viewing on GitHub Pages. 

However, most local web servers (like `python -m SimpleHTTPServer 8000`) only use HTTP 1.1 (particularly because most browsers don't support cleartext HTTP/2), which means that you'll likely see *worse* page performance when viewing locally.

**Comment by tjdett** [comment]
OK, I tried with Firefox this time (couldn't replicate with Chrome) and I see the behaviour in question. Probably because [HTML Imports](http://caniuse.com/#feat=imports) is provided by a JavaScript shim in Firefox.

Let me give it a think - there's another issue (<https://goo.gl/EGXzpw>) that also needs to be addressed.

**Comment by philippbayer** [comment]
Thank you for your answer, so it's a Firefox issue! I can confirm that it runs as expected on my laptop with Chrome.

Does the page want to support older IE? I already got a comment from the others that they can't see the date on the Perth page, <11 IE mangles the format slightly.

**Comment by tjdett** [comment]
@philippbayer Microsoft suggests strongly that IE <11 is not a good idea:
<https://www.microsoft.com/en-au/windowsforbusiness/end-of-ie-support>

Those reporting problems should probably not be surfing the web from the electron microscopy workstations. ;-)

**Comment by philippbayer** [comment]
Thank you, I can confirm that it works now
